import Head from "next/head";
import React from "react";


import DetailFeed from "../../components/detailsPage/DetailFeed";

const DetailsPage = () => {
  return (
    <div>
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0"
        />
      </Head>
      <div className="bg-gradient-to-br from-neutral-50 to-neutral-100 dark:from-neutral-900 dark:to-neutral-800 min-h-screen pt-4 pb-20">
        <DetailFeed />
      </div>
    </div>
  );
};

export default DetailsPage;
