import Head from "next/head";
import React, { useEffect } from "react";


import DetailFeed from "../../components/detailsPage/DetailFeed";

const DetailsPage = () => {
  // Lock page scroll while on the detail view
  useEffect(() => {
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prevOverflow;
    };
  }, []);

  return (
    <div className="fixed inset-0 overflow-hidden">
      <Head>
        <title>TokFlo</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0"
        />
      </Head>
      <div className="w-full h-full bg-gradient-to-br from-neutral-50 to-neutral-100 dark:from-neutral-900 dark:to-neutral-800">
        <DetailFeed />
      </div>
    </div>
  );
};

export default DetailsPage;
