import React from "react";
import Head from "next/head";

import UserProfile from "../../components/UserProfile";
import MobileNavigation from "../../components/MobileNavigation";

const User = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-neutral-50 via-white to-neutral-100 dark:from-neutral-900 dark:via-neutral-800 dark:to-neutral-900">
      <Head>
        <title>TikTok Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0"
        />
      </Head>
      <UserProfile />
      <MobileNavigation />
    </div>
  );
}

export default User;
